export async function GET() {
	const data = {
		page: 1,
		results: [
			{
				adult: false,
				backdrop_path: "/ibk375gQlUnEUyqyQpt2rCiHll7.jpg",
				id: 693134,
				title: "Dune: Part Two",
				original_language: "en",
				original_title: "Dune: Part Two",
				overview:
					"Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
				poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
				media_type: "movie",
				genre_ids: [28, 12, 878],
				popularity: 1923.174,
				release_date: "2024-02-27",
				video: false,
				vote_average: 8.5,
				vote_count: 671,
			},
			{
				adult: false,
				backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
				id: 792307,
				title: "Poor Things",
				original_language: "en",
				original_title: "Poor Things",
				overview:
					"Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
				poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
				media_type: "movie",
				genre_ids: [878, 10749, 35],
				popularity: 1680.818,
				release_date: "2023-12-07",
				video: false,
				vote_average: 8.031,
				vote_count: 1713,
			},
			{
				adult: false,
				backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
				id: 438631,
				title: "Dune",
				original_language: "en",
				original_title: "Dune",
				overview:
					"Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
				poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
				media_type: "movie",
				genre_ids: [878, 12],
				popularity: 1231.499,
				release_date: "2021-09-15",
				video: false,
				vote_average: 7.789,
				vote_count: 10405,
			},
			{
				adult: false,
				backdrop_path: "/5zmiBoMzeeVdQ62no55JOJMY498.jpg",
				id: 126308,
				name: "Shōgun",
				original_language: "en",
				original_name: "Shōgun",
				overview:
					"In Japan in the year 1600, at the dawn of a century-defining civil war, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.",
				poster_path: "/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
				media_type: "tv",
				genre_ids: [18, 10768],
				popularity: 1691.936,
				first_air_date: "2024-02-27",
				vote_average: 8.814,
				vote_count: 97,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
				id: 932420,
				title: "Code 8 Part II",
				original_language: "en",
				original_title: "Code 8 Part II",
				overview:
					"In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
				poster_path: "/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
				media_type: "movie",
				genre_ids: [878, 28, 80],
				popularity: 318.312,
				release_date: "2024-02-27",
				video: false,
				vote_average: 6.7,
				vote_count: 112,
			},
			{
				adult: false,
				backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
				id: 787699,
				title: "Wonka",
				original_language: "en",
				original_title: "Wonka",
				overview:
					"Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
				poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
				media_type: "movie",
				genre_ids: [35, 10751, 14],
				popularity: 970.109,
				release_date: "2023-12-06",
				video: false,
				vote_average: 7.205,
				vote_count: 2349,
			},
			{
				adult: false,
				backdrop_path: "/imlTCObfzISogbvcwB1dokoXAIc.jpg",
				id: 82452,
				name: "Avatar: The Last Airbender",
				original_language: "en",
				original_name: "Avatar: The Last Airbender",
				overview:
					"A young boy known as the Avatar must master the four elemental powers to save a world at war — and fight a ruthless enemy bent on stopping him.",
				poster_path: "/lzZpWEaqzP0qVA5nkCc5ASbNcSy.jpg",
				media_type: "tv",
				genre_ids: [10765, 10759, 18],
				popularity: 1889.433,
				first_air_date: "2024-02-22",
				vote_average: 8.2,
				vote_count: 377,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/zW0v2YT74C6tRafzqqBkfSqLAN0.jpg",
				id: 52814,
				name: "Halo",
				original_language: "en",
				original_name: "Halo",
				overview:
					"Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.",
				poster_path: "/hmHA5jqxN3ESIAGx0jAwV7TJhTQ.jpg",
				media_type: "tv",
				genre_ids: [10759, 10765],
				popularity: 2199.079,
				first_air_date: "2022-03-24",
				vote_average: 8.335,
				vote_count: 2327,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
				id: 1072790,
				title: "Anyone But You",
				original_language: "en",
				original_title: "Anyone But You",
				overview:
					"After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
				poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
				media_type: "movie",
				genre_ids: [35, 10749],
				popularity: 1255.003,
				release_date: "2023-12-21",
				video: false,
				vote_average: 6.975,
				vote_count: 785,
			},
			{
				adult: false,
				backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
				id: 866398,
				title: "The Beekeeper",
				original_language: "en",
				original_title: "The Beekeeper",
				overview:
					"One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
				poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
				media_type: "movie",
				genre_ids: [28, 53, 18],
				popularity: 491.478,
				release_date: "2024-01-10",
				video: false,
				vote_average: 7.433,
				vote_count: 1508,
			},
			{
				adult: false,
				backdrop_path: "/4W9kyBFT69ORP5Jzk9mVMGBBO4R.jpg",
				id: 206586,
				name: "The Walking Dead: The Ones Who Live",
				original_language: "en",
				original_name: "The Walking Dead: The Ones Who Live",
				overview:
					"The love story of Rick Grimes and Michonne is changed by a changed world. Kept apart by distance. By an unstoppable power. Can they find each other and who they were in a situation unlike any they've ever known?",
				poster_path: "/hk2dQGklfF6pwWMTzNqxbVQ56ng.jpg",
				media_type: "tv",
				genre_ids: [10765, 18],
				popularity: 1838.613,
				first_air_date: "2024-02-25",
				vote_average: 8.473,
				vote_count: 111,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
				id: 37854,
				name: "One Piece",
				original_language: "ja",
				original_name: "ワンピース",
				overview:
					'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
				poster_path: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
				media_type: "tv",
				genre_ids: [10759, 35, 16],
				popularity: 273.193,
				first_air_date: "1999-10-20",
				vote_average: 8.724,
				vote_count: 4347,
				origin_country: ["JP"],
			},
			{
				adult: false,
				backdrop_path: "/bckxSN9ueOgm0gJpVJmPQrecWul.jpg",
				id: 572802,
				title: "Aquaman and the Lost Kingdom",
				original_language: "en",
				original_title: "Aquaman and the Lost Kingdom",
				overview:
					"Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.",
				poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
				media_type: "movie",
				genre_ids: [28, 12, 14],
				popularity: 653.368,
				release_date: "2023-12-20",
				video: false,
				vote_average: 6.86,
				vote_count: 1919,
			},
			{
				adult: false,
				backdrop_path: "/aPQsU3yLDUOhLJYnSqkhKRkQTAw.jpg",
				id: 467244,
				title: "The Zone of Interest",
				original_language: "en",
				original_title: "The Zone of Interest",
				overview:
					"The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
				poster_path: "/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
				media_type: "movie",
				genre_ids: [36, 18, 10752],
				popularity: 199.317,
				release_date: "2023-12-15",
				video: false,
				vote_average: 7.35,
				vote_count: 577,
			},
			{
				adult: false,
				backdrop_path: "/82qpvU7AzT9D8oC02fIceb5KAz8.jpg",
				id: 46648,
				name: "True Detective",
				original_language: "en",
				original_name: "True Detective",
				overview:
					"An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law.",
				poster_path: "/cuV2O5ZyDLHSOWzg3nLVljp1ubw.jpg",
				media_type: "tv",
				genre_ids: [18],
				popularity: 529.686,
				first_air_date: "2014-01-12",
				vote_average: 8.304,
				vote_count: 3101,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg",
				id: 609681,
				title: "The Marvels",
				original_language: "en",
				original_title: "The Marvels",
				overview:
					"Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
				poster_path: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
				media_type: "movie",
				genre_ids: [878, 12, 28],
				popularity: 902.548,
				release_date: "2023-11-08",
				video: false,
				vote_average: 6.245,
				vote_count: 1953,
			},
			{
				adult: false,
				backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
				id: 872585,
				title: "Oppenheimer",
				original_language: "en",
				original_title: "Oppenheimer",
				overview:
					"The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
				poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
				media_type: "movie",
				genre_ids: [18, 36],
				popularity: 418.699,
				release_date: "2023-07-19",
				video: false,
				vote_average: 8.1,
				vote_count: 6928,
			},
			{
				adult: false,
				backdrop_path: "/n9NMlYd4TrSPErkRctNJaeTkGCM.jpg",
				id: 461130,
				title: "Code 8",
				original_language: "en",
				original_title: "Code 8",
				overview:
					"In Lincoln City, some inhabitants have extraordinary abilities. Most live below the poverty line, under the close surveillance of a heavily militarized police force. Connor, a construction worker with powers, involves with a criminal gang to help his ailing mother. (Based on the short film “Code 8,” 2016.)",
				poster_path: "/izGX7npHEopDQvngYcxMJEfcFbj.jpg",
				media_type: "movie",
				genre_ids: [878, 28, 80],
				popularity: 250.758,
				release_date: "2019-12-06",
				video: false,
				vote_average: 6.208,
				vote_count: 1709,
			},
			{
				adult: false,
				backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
				id: 940551,
				title: "Migration",
				original_language: "en",
				original_title: "Migration",
				overview:
					"After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
				poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
				media_type: "movie",
				genre_ids: [16, 28, 12, 35, 10751],
				popularity: 1345.241,
				release_date: "2023-12-06",
				video: false,
				vote_average: 7.606,
				vote_count: 836,
			},
			{
				adult: false,
				backdrop_path: "/6snBXmgkscLEJQmxx46qEIlqYlB.jpg",
				id: 46518,
				name: "Masters of the Air",
				original_language: "en",
				original_name: "Masters of the Air",
				overview:
					"During World War II, airmen risk their lives with the 100th Bomb Group, a brotherhood forged by courage, loss, and triumph.",
				poster_path: "/rSAmgcoA74371rplbqM27yVsd3y.jpg",
				media_type: "tv",
				genre_ids: [10768, 18],
				popularity: 386.241,
				first_air_date: "2024-01-25",
				vote_average: 7.79,
				vote_count: 124,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/pIGLdSGbdBAKu5diYFkU5nLpXkI.jpg",
				id: 197125,
				name: "Constellation",
				original_language: "en",
				original_name: "Constellation",
				overview:
					"When a fatal accident occurs on board the International Space Station, a lone astronaut makes the heroic journey back to Earth, only to discover key pieces of her life—including her young daughter—have changed.",
				poster_path: "/21ICs3fxlxGslbzS4moCHk9HNo6.jpg",
				media_type: "tv",
				genre_ids: [10765, 9648, 18],
				popularity: 372.85,
				first_air_date: "2024-02-21",
				vote_average: 8.214,
				vote_count: 56,
				origin_country: ["DE", "FR", "GB"],
			},
			{
				adult: false,
				backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
				id: 496243,
				title: "Parasite",
				original_language: "ko",
				original_title: "기생충",
				overview:
					"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
				poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
				media_type: "movie",
				genre_ids: [35, 53, 18],
				popularity: 100.683,
				release_date: "2019-05-30",
				video: false,
				vote_average: 8.51,
				vote_count: 17206,
			},
			{
				adult: false,
				backdrop_path: "/fGe1ej335XbqN1j9teoDpofpbLX.jpg",
				id: 915935,
				title: "Anatomy of a Fall",
				original_language: "fr",
				original_title: "Anatomie d'une chute",
				overview:
					"A woman is suspected of her husband’s murder, and their blind son faces a moral dilemma as the sole witness.",
				poster_path: "/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
				media_type: "movie",
				genre_ids: [53, 9648, 80],
				popularity: 157.578,
				release_date: "2023-08-23",
				video: false,
				vote_average: 7.692,
				vote_count: 1201,
			},
			{
				adult: false,
				backdrop_path: "/3mpgltEMgPf8zFtPnAWdDVN8ZT1.jpg",
				id: 1056360,
				title: "American Fiction",
				original_language: "en",
				original_title: "American Fiction",
				overview:
					'A novelist fed up with the establishment profiting from "Black" entertainment uses a pen name to write a book that propels him into the heart of hypocrisy and the madness he claims to disdain.',
				poster_path: "/57MFWGHarg9jid7yfDTka4RmcMU.jpg",
				media_type: "movie",
				genre_ids: [35, 18],
				popularity: 96.882,
				release_date: "2023-11-10",
				video: false,
				vote_average: 7.285,
				vote_count: 335,
			},
			{
				adult: false,
				backdrop_path: "/cu5Qk2QHxOyyMrD3Bq93DxgmJer.jpg",
				id: 1046090,
				title: "The Pig, the Snake and the Pigeon",
				original_language: "zh",
				original_title: "周處除三害",
				overview:
					"The arrogant, third most-wanted criminal in Taiwan, decides to get rid of the top two competitors and crowns himself the most-wanted criminal before dying.",
				poster_path: "/7IJ7F8tX7IAkpUdaGovOBJqORnJ.jpg",
				media_type: "movie",
				genre_ids: [28, 80],
				popularity: 127.519,
				release_date: "2023-10-06",
				video: false,
				vote_average: 7.9,
				vote_count: 32,
			},
			{
				adult: false,
				backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
				id: 346698,
				title: "Barbie",
				original_language: "en",
				original_title: "Barbie",
				overview:
					"Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
				poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
				media_type: "movie",
				genre_ids: [35, 12],
				popularity: 285.98,
				release_date: "2023-07-19",
				video: false,
				vote_average: 7.106,
				vote_count: 7581,
			},
			{
				adult: false,
				backdrop_path: "/xMNH87maNLt9n2bMDYeI6db5VFm.jpg",
				id: 127532,
				name: "Solo Leveling",
				original_language: "ja",
				original_name: "俺だけレベルアップな件",
				overview:
					"They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that’s leveling him up in every way. Now, he’s inspired to discover the secrets behind his powers and the dungeon that spawned them.",
				poster_path: "/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
				media_type: "tv",
				genre_ids: [16, 10759, 10765],
				popularity: 571.156,
				first_air_date: "2024-01-07",
				vote_average: 8.84,
				vote_count: 169,
				origin_country: ["JP"],
			},
			{
				adult: false,
				backdrop_path: "/2SJ6OOyK8tWaKF7W7PzYxOKKStZ.jpg",
				id: 203667,
				name: "Red Queen",
				original_language: "es",
				original_name: "Reina roja",
				overview:
					"A gifted woman's intellect brings chance to lead covert European police force. But it backfires, costing her everything. Following murder at her home and kidnapped heiress, her ex-supervisor enlists a policeman's aid to reinstate her.",
				poster_path: "/lk7LVXYSOO5rReR2jzLo8Le3cO1.jpg",
				media_type: "tv",
				genre_ids: [10759, 9648],
				popularity: 198.426,
				first_air_date: "2024-02-29",
				vote_average: 7.5,
				vote_count: 18,
				origin_country: ["ES"],
			},
			{
				adult: false,
				backdrop_path: "/du11oPPbEoDnUpiREO5tUg47rJd.jpg",
				id: 365620,
				title: "Ferrari",
				original_language: "en",
				original_title: "Ferrari",
				overview:
					"Set during the summer of 1957. Ex-racecar driver, Enzo Ferrari, is in crisis. Bankruptcy stalks the company he and his wife, Laura, built from nothing ten years earlier. Their tempestuous marriage struggles with the mourning for one son and the acknowledgement of another.",
				poster_path: "/xBFyJHvXCTgf9Vmq5uCnXRHrMQ4.jpg",
				media_type: "movie",
				genre_ids: [18, 36],
				popularity: 153.738,
				release_date: "2023-12-14",
				video: false,
				vote_average: 6.6,
				vote_count: 382,
			},
			{
				adult: false,
				backdrop_path: "/gzlprPDmKCS4bUT4BxQZmJfpMX9.jpg",
				id: 636706,
				title: "Spaceman",
				original_language: "en",
				original_title: "Spaceman",
				overview:
					"During a research mission, an astronaut discovers that his marriage is in trouble. Luckily, he has the help of a mysterious creature hidden in his ship.",
				poster_path: "/5hnFFOWEchErNVr0wMLWFEob3q1.jpg",
				media_type: "movie",
				genre_ids: [878, 18],
				popularity: 152.057,
				release_date: "2024-02-23",
				video: false,
				vote_average: 6.205,
				vote_count: 100,
			},
			{
				adult: false,
				backdrop_path: "/hx0t96Pd5AT8f2XYGHG4o8KDhIC.jpg",
				id: 233958,
				name: "The Hunter",
				original_language: "zh",
				original_name: "猎冰",
				overview:
					"A cat and mouse game between a policewoman and a drug dealer.",
				poster_path: "/acJ3v7S2BWKi6VhzX1LILtvgiYr.jpg",
				media_type: "tv",
				genre_ids: [9648, 80, 10759, 18],
				popularity: 94.798,
				first_air_date: "2024-02-21",
				vote_average: 7,
				vote_count: 5,
				origin_country: ["CN"],
			},
			{
				adult: false,
				backdrop_path: "/iWzu3dVJGNfQUkLfK9xpTWoi5mh.jpg",
				id: 1139566,
				title: "Through My Window 3: Looking at You",
				original_language: "es",
				original_title:
					"A través de mi ventana 3: A través de tu mirada",
				overview:
					"After the events of the summer, Ares and Raquel they don't see a way forward in their relationship and decide to go separate ways. But when they meet again in the winter in Barcelona, the love and desire they feel for each other is undeniable. Will they be able to find a way to get back together?",
				poster_path: "/gwpTgtwVAwmvivBN8rAQABpx9Am.jpg",
				media_type: "movie",
				genre_ids: [10749, 18, 35],
				popularity: 803.243,
				release_date: "2024-02-23",
				video: false,
				vote_average: 6.837,
				vote_count: 205,
			},
			{
				adult: false,
				backdrop_path: "/3Kzc6V4MWs3RXCmE5DhAYnfWL8F.jpg",
				id: 1239251,
				title: "Megamind vs. the Doom Syndicate",
				original_language: "en",
				original_title: "Megamind vs. the Doom Syndicate",
				overview:
					"Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
				poster_path: "/1N7terrMeZPwK5qq31MUD0HQ3IG.jpg",
				media_type: "movie",
				genre_ids: [16, 35, 878],
				popularity: 148.121,
				release_date: "2024-03-01",
				video: false,
				vote_average: 6.2,
				vote_count: 52,
			},
			{
				adult: false,
				backdrop_path: "/egg9DiLuzgINodXO4I2zGm8eIOL.jpg",
				id: 1039882,
				title: "My Name Is Loh Kiwan",
				original_language: "ko",
				original_title: "로기완",
				overview:
					"After defecting from North Korea, Loh Kiwan struggles to obtain refugee status in Belgium, where he encounters a dejected woman who has lost all hope.",
				poster_path: "/x4BkphLO6abbGhceYEMhJERkvHo.jpg",
				media_type: "movie",
				genre_ids: [10749, 18],
				popularity: 39.691,
				release_date: "2024-02-19",
				video: false,
				vote_average: 7.25,
				vote_count: 16,
			},
			{
				adult: false,
				backdrop_path: "/rIe3PnM6S7IBUmvNwDkBMX0i9EZ.jpg",
				id: 1399,
				name: "Game of Thrones",
				original_language: "en",
				original_name: "Game of Thrones",
				overview:
					"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
				poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
				media_type: "tv",
				genre_ids: [10765, 18, 10759],
				popularity: 1204.355,
				first_air_date: "2011-04-17",
				vote_average: 8.445,
				vote_count: 22736,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg",
				id: 695721,
				title: "The Hunger Games: The Ballad of Songbirds & Snakes",
				original_language: "en",
				original_title:
					"The Hunger Games: The Ballad of Songbirds & Snakes",
				overview:
					"64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
				poster_path: "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
				media_type: "movie",
				genre_ids: [18, 878, 28],
				popularity: 298.802,
				release_date: "2023-11-15",
				video: false,
				vote_average: 7.185,
				vote_count: 1898,
			},
			{
				adult: false,
				backdrop_path: "/nvW0QfRJ7ga9TK8DKwBfAPA8ywP.jpg",
				id: 944401,
				title: "Dogman",
				original_language: "en",
				original_title: "Dogman",
				overview:
					"A boy, bruised by life, finds his salvation through the love of his dogs.",
				poster_path: "/rmRkZZ2aZq72dDTjbPnSLtPQcmJ.jpg",
				media_type: "movie",
				genre_ids: [28, 18, 80],
				popularity: 139.882,
				release_date: "2023-09-27",
				video: false,
				vote_average: 7.409,
				vote_count: 317,
			},
			{
				adult: false,
				backdrop_path: "/xs2v0K7iKAuR4YtKOw7TEcDIX63.jpg",
				id: 105971,
				name: "Star Wars: The Bad Batch",
				original_language: "en",
				original_name: "Star Wars: The Bad Batch",
				overview:
					"The 'Bad Batch' of elite and experimental clones make their way through an ever-changing galaxy in the immediate aftermath of the Clone Wars.",
				poster_path: "/5mHus672nuinyaE0FtqvD0AddcY.jpg",
				media_type: "tv",
				genre_ids: [16, 10759, 10765],
				popularity: 206.391,
				first_air_date: "2021-05-04",
				vote_average: 8.239,
				vote_count: 873,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/4l65BWqJBl7hBwdIwp2nQdwsOuw.jpg",
				id: 850165,
				title: "The Iron Claw",
				original_language: "en",
				original_title: "The Iron Claw",
				overview:
					"The true story of the inseparable Von Erich brothers, who made history in the intensely competitive world of professional wrestling in the early 1980s. Through tragedy and triumph, under the shadow of their domineering father and coach, the brothers seek larger-than-life immortality on the biggest stage in sports.",
				poster_path: "/nfs7DCYhgrEIgxKYbITHTzKsggf.jpg",
				media_type: "movie",
				genre_ids: [18, 36],
				popularity: 111.261,
				release_date: "2023-12-21",
				video: false,
				vote_average: 7.532,
				vote_count: 311,
			},
			{
				adult: false,
				backdrop_path: "/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
				id: 1429,
				name: "Attack on Titan",
				original_language: "ja",
				original_name: "進撃の巨人",
				overview:
					"Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
				poster_path: "/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
				media_type: "tv",
				genre_ids: [16, 10765, 10759],
				popularity: 174.431,
				first_air_date: "2013-04-07",
				vote_average: 8.66,
				vote_count: 5934,
				origin_country: ["JP"],
			},
		],
		total_pages: 1000,
		total_results: 20000,
	};

	return Response.json({ data });
}
