import { Inter } from "next/font/google";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "webflix",
	description: "Generated by create next app",
	icons: {
		icon: "/logo/logo.png",
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="flex-1">{children}</main>
			</body>
		</html>
	);
}
