import { Inter } from "next/font/google";
import "./globals.css";

import NavBar from "./components/navbar";
import Footer from "./components/footer";

import Scrollbar from "./components/scrollbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "webflix",
	description: "Generated by create next app",
	icons: {
		icon: "/logo/logo.png",
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="relative flex min-h-screen flex-col bg-background">
					<Scrollbar />
					<NavBar />
					<main className="flex-1">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
