export async function GET(request) {
	const searchParams = request.nextUrl.searchParams;
	const query = searchParams.get("type");
	var data = {};
	if (query === "week") {
		data = {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: "/ibk375gQlUnEUyqyQpt2rCiHll7.jpg",
					id: 693134,
					title: "Dune: Part Two",
					original_language: "en",
					original_title: "Dune: Part Two",
					overview:
						"Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
					poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
					media_type: "movie",
					genre_ids: [28, 12, 878],
					popularity: 1923.174,
					release_date: "2024-02-27",
					video: false,
					vote_average: 8.5,
					vote_count: 671,
				},
				{
					adult: false,
					backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
					id: 792307,
					title: "Poor Things",
					original_language: "en",
					original_title: "Poor Things",
					overview:
						"Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
					poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
					media_type: "movie",
					genre_ids: [878, 10749, 35],
					popularity: 1680.818,
					release_date: "2023-12-07",
					video: false,
					vote_average: 8.031,
					vote_count: 1713,
				},
				{
					adult: false,
					backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
					id: 438631,
					title: "Dune",
					original_language: "en",
					original_title: "Dune",
					overview:
						"Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
					poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
					media_type: "movie",
					genre_ids: [878, 12],
					popularity: 1231.499,
					release_date: "2021-09-15",
					video: false,
					vote_average: 7.789,
					vote_count: 10405,
				},
				{
					adult: false,
					backdrop_path: "/5zmiBoMzeeVdQ62no55JOJMY498.jpg",
					id: 126308,
					name: "Shōgun",
					original_language: "en",
					original_name: "Shōgun",
					overview:
						"In Japan in the year 1600, at the dawn of a century-defining civil war, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.",
					poster_path: "/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
					media_type: "tv",
					genre_ids: [18, 10768],
					popularity: 1691.936,
					first_air_date: "2024-02-27",
					vote_average: 8.814,
					vote_count: 97,
					origin_country: ["US"],
				},
				{
					adult: false,
					backdrop_path: "/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
					id: 932420,
					title: "Code 8 Part II",
					original_language: "en",
					original_title: "Code 8 Part II",
					overview:
						"In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
					poster_path: "/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
					media_type: "movie",
					genre_ids: [878, 28, 80],
					popularity: 318.312,
					release_date: "2024-02-27",
					video: false,
					vote_average: 6.7,
					vote_count: 112,
				},
				{
					adult: false,
					backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
					id: 787699,
					title: "Wonka",
					original_language: "en",
					original_title: "Wonka",
					overview:
						"Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
					poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
					media_type: "movie",
					genre_ids: [35, 10751, 14],
					popularity: 970.109,
					release_date: "2023-12-06",
					video: false,
					vote_average: 7.205,
					vote_count: 2349,
				},
				{
					adult: false,
					backdrop_path: "/imlTCObfzISogbvcwB1dokoXAIc.jpg",
					id: 82452,
					name: "Avatar: The Last Airbender",
					original_language: "en",
					original_name: "Avatar: The Last Airbender",
					overview:
						"A young boy known as the Avatar must master the four elemental powers to save a world at war — and fight a ruthless enemy bent on stopping him.",
					poster_path: "/lzZpWEaqzP0qVA5nkCc5ASbNcSy.jpg",
					media_type: "tv",
					genre_ids: [10765, 10759, 18],
					popularity: 1889.433,
					first_air_date: "2024-02-22",
					vote_average: 8.2,
					vote_count: 377,
					origin_country: ["US"],
				},
				{
					adult: false,
					backdrop_path: "/zW0v2YT74C6tRafzqqBkfSqLAN0.jpg",
					id: 52814,
					name: "Halo",
					original_language: "en",
					original_name: "Halo",
					overview:
						"Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.",
					poster_path: "/hmHA5jqxN3ESIAGx0jAwV7TJhTQ.jpg",
					media_type: "tv",
					genre_ids: [10759, 10765],
					popularity: 2199.079,
					first_air_date: "2022-03-24",
					vote_average: 8.335,
					vote_count: 2327,
					origin_country: ["US"],
				},
				{
					adult: false,
					backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
					id: 1072790,
					title: "Anyone But You",
					original_language: "en",
					original_title: "Anyone But You",
					overview:
						"After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
					poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
					media_type: "movie",
					genre_ids: [35, 10749],
					popularity: 1255.003,
					release_date: "2023-12-21",
					video: false,
					vote_average: 6.975,
					vote_count: 785,
				},
				{
					adult: false,
					backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
					id: 866398,
					title: "The Beekeeper",
					original_language: "en",
					original_title: "The Beekeeper",
					overview:
						"One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
					poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
					media_type: "movie",
					genre_ids: [28, 53, 18],
					popularity: 491.478,
					release_date: "2024-01-10",
					video: false,
					vote_average: 7.433,
					vote_count: 1508,
				},
				{
					adult: false,
					backdrop_path: "/4W9kyBFT69ORP5Jzk9mVMGBBO4R.jpg",
					id: 206586,
					name: "The Walking Dead: The Ones Who Live",
					original_language: "en",
					original_name: "The Walking Dead: The Ones Who Live",
					overview:
						"The love story of Rick Grimes and Michonne is changed by a changed world. Kept apart by distance. By an unstoppable power. Can they find each other and who they were in a situation unlike any they've ever known?",
					poster_path: "/hk2dQGklfF6pwWMTzNqxbVQ56ng.jpg",
					media_type: "tv",
					genre_ids: [10765, 18],
					popularity: 1838.613,
					first_air_date: "2024-02-25",
					vote_average: 8.473,
					vote_count: 111,
					origin_country: ["US"],
				},
				{
					adult: false,
					backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
					id: 37854,
					name: "One Piece",
					original_language: "ja",
					original_name: "ワンピース",
					overview:
						'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
					poster_path: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
					media_type: "tv",
					genre_ids: [10759, 35, 16],
					popularity: 273.193,
					first_air_date: "1999-10-20",
					vote_average: 8.724,
					vote_count: 4347,
					origin_country: ["JP"],
				},
				{
					adult: false,
					backdrop_path: "/bckxSN9ueOgm0gJpVJmPQrecWul.jpg",
					id: 572802,
					title: "Aquaman and the Lost Kingdom",
					original_language: "en",
					original_title: "Aquaman and the Lost Kingdom",
					overview:
						"Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.",
					poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
					media_type: "movie",
					genre_ids: [28, 12, 14],
					popularity: 653.368,
					release_date: "2023-12-20",
					video: false,
					vote_average: 6.86,
					vote_count: 1919,
				},
				{
					adult: false,
					backdrop_path: "/aPQsU3yLDUOhLJYnSqkhKRkQTAw.jpg",
					id: 467244,
					title: "The Zone of Interest",
					original_language: "en",
					original_title: "The Zone of Interest",
					overview:
						"The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
					poster_path: "/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
					media_type: "movie",
					genre_ids: [36, 18, 10752],
					popularity: 199.317,
					release_date: "2023-12-15",
					video: false,
					vote_average: 7.35,
					vote_count: 577,
				},
				{
					adult: false,
					backdrop_path: "/82qpvU7AzT9D8oC02fIceb5KAz8.jpg",
					id: 46648,
					name: "True Detective",
					original_language: "en",
					original_name: "True Detective",
					overview:
						"An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law.",
					poster_path: "/cuV2O5ZyDLHSOWzg3nLVljp1ubw.jpg",
					media_type: "tv",
					genre_ids: [18],
					popularity: 529.686,
					first_air_date: "2014-01-12",
					vote_average: 8.304,
					vote_count: 3101,
					origin_country: ["US"],
				},
				{
					adult: false,
					backdrop_path: "/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg",
					id: 609681,
					title: "The Marvels",
					original_language: "en",
					original_title: "The Marvels",
					overview:
						"Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
					poster_path: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
					media_type: "movie",
					genre_ids: [878, 12, 28],
					popularity: 902.548,
					release_date: "2023-11-08",
					video: false,
					vote_average: 6.245,
					vote_count: 1953,
				},
				{
					adult: false,
					backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
					id: 872585,
					title: "Oppenheimer",
					original_language: "en",
					original_title: "Oppenheimer",
					overview:
						"The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
					poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
					media_type: "movie",
					genre_ids: [18, 36],
					popularity: 418.699,
					release_date: "2023-07-19",
					video: false,
					vote_average: 8.1,
					vote_count: 6928,
				},
				{
					adult: false,
					backdrop_path: "/n9NMlYd4TrSPErkRctNJaeTkGCM.jpg",
					id: 461130,
					title: "Code 8",
					original_language: "en",
					original_title: "Code 8",
					overview:
						"In Lincoln City, some inhabitants have extraordinary abilities. Most live below the poverty line, under the close surveillance of a heavily militarized police force. Connor, a construction worker with powers, involves with a criminal gang to help his ailing mother. (Based on the short film “Code 8,” 2016.)",
					poster_path: "/izGX7npHEopDQvngYcxMJEfcFbj.jpg",
					media_type: "movie",
					genre_ids: [878, 28, 80],
					popularity: 250.758,
					release_date: "2019-12-06",
					video: false,
					vote_average: 6.208,
					vote_count: 1709,
				},
				{
					adult: false,
					backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
					id: 940551,
					title: "Migration",
					original_language: "en",
					original_title: "Migration",
					overview:
						"After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
					poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
					media_type: "movie",
					genre_ids: [16, 28, 12, 35, 10751],
					popularity: 1345.241,
					release_date: "2023-12-06",
					video: false,
					vote_average: 7.606,
					vote_count: 836,
				},
				{
					adult: false,
					backdrop_path: "/6snBXmgkscLEJQmxx46qEIlqYlB.jpg",
					id: 46518,
					name: "Masters of the Air",
					original_language: "en",
					original_name: "Masters of the Air",
					overview:
						"During World War II, airmen risk their lives with the 100th Bomb Group, a brotherhood forged by courage, loss, and triumph.",
					poster_path: "/rSAmgcoA74371rplbqM27yVsd3y.jpg",
					media_type: "tv",
					genre_ids: [10768, 18],
					popularity: 386.241,
					first_air_date: "2024-01-25",
					vote_average: 7.79,
					vote_count: 124,
					origin_country: ["US"],
				},
			],
			total_pages: 1000,
			total_results: 20000,
		};
	} else if (query === "animation") {
		data = {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
					genre_ids: [16, 28, 12, 35, 10751],
					id: 940551,
					original_language: "en",
					original_title: "Migration",
					overview:
						"After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
					popularity: 898.239,
					poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
					release_date: "2023-12-06",
					title: "Migration",
					video: false,
					vote_average: 7.603,
					vote_count: 857,
				},
				{
					adult: false,
					backdrop_path: "/fCwwzOziFYs7YRwP4gbrb9qH1xg.jpg",
					genre_ids: [28, 12, 16, 35, 10751],
					id: 1011985,
					original_language: "en",
					original_title: "Kung Fu Panda 4",
					overview:
						"Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
					popularity: 605.84,
					poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
					release_date: "2024-03-02",
					title: "Kung Fu Panda 4",
					video: false,
					vote_average: 7.8,
					vote_count: 9,
				},
				{
					adult: false,
					backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
					genre_ids: [16, 10751, 14, 12],
					id: 1022796,
					original_language: "en",
					original_title: "Wish",
					overview:
						"Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
					popularity: 414.585,
					poster_path: "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
					release_date: "2023-11-13",
					title: "Wish",
					video: false,
					vote_average: 6.604,
					vote_count: 836,
				},
				{
					adult: false,
					backdrop_path: "/arT10FrsPdxJOFBrHMrVvoDJCqR.jpg",
					genre_ids: [16, 35, 878, 10751, 12],
					id: 1078012,
					original_language: "zh",
					original_title: "熊出没·伴我“熊芯”",
					overview:
						"Briar and Bramble, who lost their mother Barbara when they were cubs, are thrown into danger when escorting a scientist, which may lead them to a family reunion.",
					popularity: 279.803,
					poster_path: "/lIR8h3Os8peWOave8CGE7xsTFoi.jpg",
					release_date: "2023-01-22",
					title: "Boonie Bears: Guardian Code",
					video: false,
					vote_average: 7,
					vote_count: 4,
				},
				{
					adult: false,
					backdrop_path: "/zLj0peaxy5y2SlC6wNIQ4V0pfqg.jpg",
					genre_ids: [16, 10751, 35, 14],
					id: 1139829,
					original_language: "en",
					original_title: "Orion and the Dark",
					overview:
						"A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.",
					popularity: 268.1,
					poster_path: "/uHiXFLMlnl5jBjtfOliapN16yBD.jpg",
					release_date: "2024-02-02",
					title: "Orion and the Dark",
					video: false,
					vote_average: 6.7,
					vote_count: 298,
				},
				{
					adult: false,
					backdrop_path: "/3Kzc6V4MWs3RXCmE5DhAYnfWL8F.jpg",
					genre_ids: [16, 35, 878],
					id: 1239251,
					original_language: "en",
					original_title: "Megamind vs. the Doom Syndicate",
					overview:
						"Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
					popularity: 406.444,
					poster_path: "/1N7terrMeZPwK5qq31MUD0HQ3IG.jpg",
					release_date: "2024-03-01",
					title: "Megamind vs. the Doom Syndicate",
					video: false,
					vote_average: 6.156,
					vote_count: 64,
				},
				{
					adult: false,
					backdrop_path: "/midCh3iVxaG3dUOrP9TnUpNcGm.jpg",
					genre_ids: [16, 12, 14],
					id: 508883,
					original_language: "ja",
					original_title: "君たちはどう生きるか",
					overview:
						"While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
					popularity: 227.744,
					poster_path: "/jDQPkgzerGophKRRn7MKm071vCU.jpg",
					release_date: "2023-07-14",
					title: "The Boy and the Heron",
					video: false,
					vote_average: 7.477,
					vote_count: 1022,
				},
				{
					adult: false,
					backdrop_path: "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
					genre_ids: [16, 10751, 12, 14, 35],
					id: 502356,
					original_language: "en",
					original_title: "The Super Mario Bros. Movie",
					overview:
						"While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
					popularity: 219.203,
					poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
					release_date: "2023-04-05",
					title: "The Super Mario Bros. Movie",
					video: false,
					vote_average: 7.691,
					vote_count: 8109,
				},
				{
					adult: false,
					backdrop_path: "/8b1oWeOQLSwQH6TK3T0b1oNl3Al.jpg",
					genre_ids: [16, 18, 10751, 36],
					id: 676727,
					original_language: "en",
					original_title: "The Inventor",
					overview:
						'The insatiably curious and headstrong inventor Leonardo da Vinci leaves Italy to join the French court, where he can experiment freely, inventing flying contraptions, incredible machines, and study the human body. There, joined in his adventure by the audacious princess Marguerite, Leonardo will uncover the answer to the ultimate question – "What is the meaning of it all?"',
					popularity: 188.301,
					poster_path: "/7Rpo5S3GjORu3yjah0o9eLcllSj.jpg",
					release_date: "2023-09-15",
					title: "The Inventor",
					video: false,
					vote_average: 5.778,
					vote_count: 9,
				},
				{
					adult: false,
					backdrop_path: "/9xfDWXAUbFXQK585JvByT5pEAhe.jpg",
					genre_ids: [16, 28, 12, 878],
					id: 569094,
					original_language: "en",
					original_title: "Spider-Man: Across the Spider-Verse",
					overview:
						"After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
					popularity: 187.011,
					poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
					release_date: "2023-05-31",
					title: "Spider-Man: Across the Spider-Verse",
					video: false,
					vote_average: 8.38,
					vote_count: 5901,
				},
				{
					adult: false,
					backdrop_path: "/2BVFrn3X8uH3hJh2403RMkiEgzF.jpg",
					genre_ids: [16, 80, 28],
					id: 1220441,
					original_language: "ja",
					original_title: "GREAT PRETENDER razbliuto",
					overview:
						"Presumed dead, master con artist and recovering amnesiac Dorothy is discovered by Shanghai Longu-bang, a mob who wants payback for her conning them. With no memories and nowhere to go, she must rely on a local crime underboss to elude Taipei's criminal underworld all while tracking down leads to her mysterious past.",
					popularity: 189.385,
					poster_path: "/gQwzIIyhgsFiYiXI7fNpTUvWghP.jpg",
					release_date: "2024-01-09",
					title: "GREAT PRETENDER razbliuto",
					video: false,
					vote_average: 6,
					vote_count: 3,
				},
				{
					adult: false,
					backdrop_path: "/zMtBbNhROxPf0urHSBoZUnqJEwT.jpg",
					genre_ids: [16, 10751, 10402, 14, 35],
					id: 901362,
					original_language: "en",
					original_title: "Trolls Band Together",
					overview:
						"When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
					popularity: 164.29,
					poster_path: "/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
					release_date: "2023-10-12",
					title: "Trolls Band Together",
					video: false,
					vote_average: 7.314,
					vote_count: 675,
				},
				{
					adult: false,
					backdrop_path: "/acpFrSmVLnTNAIuHxnZArkC3dwU.jpg",
					genre_ids: [16, 28, 12, 10751, 14],
					id: 598387,
					original_language: "en",
					original_title: "The Tiger's Apprentice",
					overview:
						"After the death of his grandmother, Tom Lee discovers he is part of a long lineage of magical protectors known as the Guardians. With guidance from a mythical tiger named Hu and the other Zodiac animal warriors, Tom trains to take on an evil force that threatens humanity.",
					popularity: 178.142,
					poster_path: "/iiid1xMhoAcW83VJ9LdAqf4Vtbr.jpg",
					release_date: "2024-02-02",
					title: "The Tiger's Apprentice",
					video: false,
					vote_average: 7.308,
					vote_count: 91,
				},
				{
					adult: false,
					backdrop_path: "/pA4sNvcohTNPx3AhEEeIu8gSt7h.jpg",
					genre_ids: [16, 35, 10751, 14, 10749, 12],
					id: 976573,
					original_language: "en",
					original_title: "Elemental",
					overview:
						"In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
					popularity: 174.368,
					poster_path: "/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
					release_date: "2023-06-14",
					title: "Elemental",
					video: false,
					vote_average: 7.667,
					vote_count: 3763,
				},
				{
					adult: false,
					backdrop_path: "/8NEvnVKeGMLEXG45MMNqxJLcM4y.jpg",
					genre_ids: [28, 16, 14],
					id: 820232,
					original_language: "ja",
					original_title: "鬼滅の刃 兄妹の絆",
					overview:
						"Tanjiro finds his family slaughtered and the lone survivor, his sister Nezuko Kamado, turned into a Demon. To his surprise, however, Nezuko still shows signs of human emotion and thought. Thus begins Tanjiro's journey to seek out the Demon who killed their family and turn his sister human again. A recap film of Kimetsu no Yaiba, covering episodes 1-5 with extra footage.",
					popularity: 172.566,
					poster_path: "/vJUDoYNNKvBqbEPUskgvzPXGEFz.jpg",
					release_date: "2019-03-29",
					title: "Demon Slayer: Kimetsu no Yaiba Sibling's Bond",
					video: false,
					vote_average: 7.929,
					vote_count: 183,
				},
				{
					adult: false,
					backdrop_path: "/auXrHU6O17n9Tz11SHReoorjrU6.jpg",
					genre_ids: [16, 35, 10751],
					id: 1075794,
					original_language: "en",
					original_title: "Leo",
					overview:
						"Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.",
					popularity: 168.341,
					poster_path: "/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
					release_date: "2023-11-17",
					title: "Leo",
					video: false,
					vote_average: 7.492,
					vote_count: 970,
				},
				{
					adult: false,
					backdrop_path: "/hIeEpk2w1dnC9ly9ZJwwbunH2Cx.jpg",
					genre_ids: [16, 35, 18, 10751],
					id: 838240,
					original_language: "es",
					original_title: "Robot Dreams",
					overview:
						"Dog lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of 80's NYC. One summer night, Dog, with great sadness, is forced to abandon Robot at the beach. Will they ever meet again?",
					popularity: 146.064,
					poster_path: "/qLtK6DFeuJNuB3THGVDklirhQ8u.jpg",
					release_date: "2023-10-20",
					title: "Robot Dreams",
					video: false,
					vote_average: 7.3,
					vote_count: 84,
				},
				{
					adult: false,
					backdrop_path: "/2q3B90h2hZ6xJTvna9CIFDNaIr4.jpg",
					genre_ids: [16, 35],
					id: 9473,
					original_language: "en",
					original_title: "South Park: Bigger, Longer & Uncut",
					overview:
						'When the four boys see an R-rated movie featuring Canadians Terrance and Philip, they are pronounced "corrupted", and their parents pressure the United States to wage war against Canada.',
					popularity: 227.623,
					poster_path: "/tS0PedvA2mFO9VCHYwQpaU1K36U.jpg",
					release_date: "1999-06-30",
					title: "South Park: Bigger, Longer & Uncut",
					video: false,
					vote_average: 7.261,
					vote_count: 2538,
				},
				{
					adult: false,
					backdrop_path: "/d1RHScaZc7I8j0lDke1c4AxI435.jpg",
					genre_ids: [28, 12, 16, 10751, 35],
					id: 9502,
					original_language: "en",
					original_title: "Kung Fu Panda",
					overview:
						"When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the \"chosen one\" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won't be easy. It's up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.",
					popularity: 175.729,
					poster_path: "/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg",
					release_date: "2008-06-04",
					title: "Kung Fu Panda",
					video: false,
					vote_average: 7.265,
					vote_count: 10901,
				},
				{
					adult: false,
					backdrop_path: "/pW1sEV4R2GL99OoUq73Pvf7r7Ce.jpg",
					genre_ids: [16, 35, 18],
					id: 24238,
					original_language: "en",
					original_title: "Mary and Max",
					overview:
						"A tale of friendship between two unlikely pen pals: Mary, a lonely, eight-year-old girl living in the suburbs of Melbourne, and Max, a forty-four-year old, severely obese man living in New York.",
					popularity: 136.441,
					poster_path: "/b4LKlquh0ls5Rgb27QLPlkC7Oya.jpg",
					release_date: "2009-02-09",
					title: "Mary and Max",
					video: false,
					vote_average: 7.848,
					vote_count: 1854,
				},
			],
			total_pages: 2557,
			total_results: 51136,
		};
	} else if (query === "docu") {
		data = {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
					genre_ids: [18],
					id: 100088,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Last of Us",
					overview:
						"Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
					popularity: 188.561,
					poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
					first_air_date: "2023-01-15",
					name: "The Last of Us",
					vote_average: 8.622,
					vote_count: 4551,
				},
				{
					adult: false,
					backdrop_path: "/qD211Hb5XwFxrszzBBe5EUYJerh.jpg",
					genre_ids: [10759, 10765],
					id: 111110,
					origin_country: ["US"],
					original_language: "en",
					original_name: "ONE PIECE",
					overview:
						"With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure.",
					popularity: 135.732,
					poster_path: "/rVX05xRKS5JhEYQFObCi4lAnZT4.jpg",
					first_air_date: "2023-08-31",
					name: "ONE PIECE",
					vote_average: 8.2,
					vote_count: 963,
				},
				{
					adult: false,
					backdrop_path: "/57clBMPX25NNO6nmDw3TV3zQaQE.jpg",
					genre_ids: [18, 10765, 10759],
					id: 114472,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Secret Invasion",
					overview:
						"Nick Fury and Talos discover a faction of shapeshifting Skrulls who have been infiltrating Earth for years.",
					popularity: 103.844,
					poster_path: "/f5ZMzzCvt2IzVDxr54gHPv9jlC9.jpg",
					first_air_date: "2023-06-21",
					name: "Secret Invasion",
					vote_average: 6.868,
					vote_count: 926,
				},
				{
					adult: false,
					backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
					genre_ids: [18],
					id: 125988,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Silo",
					overview:
						"In a ruined and toxic future, a community exists in a giant underground silo that plunges hundreds of stories deep. There, men and women live in a society full of regulations they believe are meant to protect them.",
					popularity: 155.097,
					poster_path: "/zBx1X06G1OlndbXTCZI13FECNz2.jpg",
					first_air_date: "2023-05-04",
					name: "Silo",
					vote_average: 8.198,
					vote_count: 731,
				},
				{
					adult: false,
					backdrop_path: "/AvsNXUbP7UKCVnypyx2eWp8z2N3.jpg",
					genre_ids: [16, 35, 10765],
					id: 94954,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Hazbin Hotel",
					overview:
						"In attempt to find a non-violent alternative for reducing Hell's overpopulation, the daughter of Lucifer opens a rehabilitation hotel that offers a group of misfit demons a chance at redemption.",
					popularity: 330.388,
					poster_path: "/rXojaQcxVUubPLSrFV8PD4xdjrs.jpg",
					first_air_date: "2024-01-18",
					name: "Hazbin Hotel",
					vote_average: 9.058,
					vote_count: 681,
				},
				{
					adult: false,
					backdrop_path: "/31GIcUUcdQPRkVtmdqgQWJMhXj1.jpg",
					genre_ids: [10765, 10759],
					id: 114461,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Ahsoka",
					overview:
						"Former Jedi Knight Ahsoka Tano investigates an emerging threat to a vulnerable galaxy.",
					popularity: 97.102,
					poster_path: "/laCJxobHoPVaLQTKxc14Y2zV64J.jpg",
					first_air_date: "2023-08-22",
					name: "Ahsoka",
					vote_average: 7.667,
					vote_count: 665,
				},
				{
					adult: false,
					backdrop_path: "/urzEsxKKNgCan2mX5z5heXbUyef.jpg",
					genre_ids: [10759, 18, 10765],
					id: 205715,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Gen V",
					overview:
						"At America's only college for superheroes, gifted students put their moral boundaries to the test, competing for the university's top ranking, and a chance to join The Seven, Vought International's elite superhero team. When the school's dark secrets come to light, they must decide what kind of heroes they want to become.",
					popularity: 102.603,
					poster_path: "/uuot1N5AgZ7xRCKgm4ZCwOhgIJu.jpg",
					first_air_date: "2023-09-28",
					name: "Gen V",
					vote_average: 8.001,
					vote_count: 645,
				},
				{
					adult: false,
					backdrop_path: "/lghMCJJ7u2fIHMVtsrsMCV9OTsI.jpg",
					genre_ids: [10759, 18, 10765],
					id: 202411,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Monarch: Legacy of Monsters",
					overview:
						"After surviving Godzilla's attack on San Francisco, Cate is shaken yet again by a shocking secret. Amid monstrous threats, she embarks on a globetrotting adventure to learn the truth about her family—and the mysterious organization known as Monarch.",
					popularity: 221.765,
					poster_path: "/uwrQHMnXD2DA1rvaMZk4pavZ3CY.jpg",
					first_air_date: "2023-11-16",
					name: "Monarch: Legacy of Monsters",
					vote_average: 8.019,
					vote_count: 609,
				},
				{
					adult: false,
					backdrop_path: "/vLN520GJvHJJQOFqqV7RjZNBwi7.jpg",
					genre_ids: [18, 9648, 10759],
					id: 129552,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Night Agent",
					overview:
						"While monitoring an emergency line, a vigilant FBI agent answers a call that plunges him into a deadly conspiracy involving a mole at the White House.",
					popularity: 87.729,
					poster_path: "/xjsx6rGEgHl2tUqkimo6Bz2KzVo.jpg",
					first_air_date: "2023-03-23",
					name: "The Night Agent",
					vote_average: 7.874,
					vote_count: 571,
				},
				{
					adult: false,
					backdrop_path: "/sa9vB0xb3OMU6iSMkig8RBbdESq.jpg",
					genre_ids: [18],
					id: 113962,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Special Ops: Lioness",
					overview:
						"Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA’s Lioness Engagement Team to help bring down a terrorist organization from within. Joe, the station chief of the Lioness program, is tasked with training, managing and leading her female undercover operatives.",
					popularity: 110.732,
					poster_path: "/rXCzevakJoAN1qnZY0nAQPSLVRv.jpg",
					first_air_date: "2023-07-23",
					name: "Special Ops: Lioness",
					vote_average: 8.045,
					vote_count: 522,
				},
				{
					adult: false,
					backdrop_path: "/u7OpeS4eckBSR1wFxFTuyy3FjHE.jpg",
					genre_ids: [35, 18],
					id: 154385,
					origin_country: ["US"],
					original_language: "en",
					original_name: "BEEF",
					overview:
						"A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.",
					popularity: 69.305,
					poster_path: "/4b4v7RnPhNyPEaVGFarEuo74r8W.jpg",
					first_air_date: "2023-04-06",
					name: "BEEF",
					vote_average: 7.845,
					vote_count: 480,
				},
				{
					adult: false,
					backdrop_path: "/uPhsA9a2PtUYwYgECZKkOQOyL7c.jpg",
					genre_ids: [18],
					id: 198102,
					origin_country: ["GB"],
					original_language: "en",
					original_name: "Hijack",
					overview:
						"When Flight KA29 is hijacked during its seven-hour journey from Dubai to London, Sam Nelson—an accomplished corporate negotiator—tries using his professional skills to save everyone on board. Will this high-risk strategy be his undoing?",
					popularity: 81.334,
					poster_path: "/szDEqqarPi3YqiPLevm7LObYrDJ.jpg",
					first_air_date: "2023-06-28",
					name: "Hijack",
					vote_average: 7.947,
					vote_count: 417,
				},
				{
					adult: false,
					backdrop_path: "/imlTCObfzISogbvcwB1dokoXAIc.jpg",
					genre_ids: [10765, 10759, 18],
					id: 82452,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Avatar: The Last Airbender",
					overview:
						"A young boy known as the Avatar must master the four elemental powers to save a world at war — and fight a ruthless enemy bent on stopping him.",
					popularity: 1393.277,
					poster_path: "/lzZpWEaqzP0qVA5nkCc5ASbNcSy.jpg",
					first_air_date: "2024-02-22",
					name: "Avatar: The Last Airbender",
					vote_average: 8.19,
					vote_count: 428,
				},
				{
					adult: false,
					backdrop_path: "/4qDlkEAKFb4pgIUbeJMLyHX2Xym.jpg",
					genre_ids: [80, 18, 9648],
					id: 157065,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Fall of the House of Usher",
					overview:
						"Ruthless siblings Roderick and Madeline Usher have built Fortunato Pharmaceuticals into an empire of wealth, privilege and power. But past secrets come to light when the heirs to the Usher dynasty start dying at the hands of a mysterious woman from their youth.",
					popularity: 65.268,
					poster_path: "/2rl04pRCaGfz91lwfWdDQmOiGJp.jpg",
					first_air_date: "2023-10-12",
					name: "The Fall of the House of Usher",
					vote_average: 7.646,
					vote_count: 397,
				},
				{
					adult: false,
					backdrop_path: "/fkeVnvxVx4x2PdDOOzSblFUGTVt.jpg",
					genre_ids: [10765, 10759, 18],
					id: 211684,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Walking Dead: Daryl Dixon",
					overview:
						"Daryl washes ashore in France and struggles to piece together how he got there and why. The series tracks his journey across a broken but resilient France as he hopes to find a way back home. As he makes the journey, though, the connections he forms along the way complicate his ultimate plan.",
					popularity: 238.215,
					poster_path: "/kdM24KINoAVK9wjCtDJCkdffEpc.jpg",
					first_air_date: "2023-09-10",
					name: "The Walking Dead: Daryl Dixon",
					vote_average: 8.303,
					vote_count: 393,
				},
				{
					adult: false,
					backdrop_path: "/vV5LKWmuysEe5wsuZJGbdiL5XJ2.jpg",
					genre_ids: [10759, 18, 10765],
					id: 194583,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Walking Dead: Dead City",
					overview:
						"Maggie and Negan travel to post-apocalyptic Manhattan - long ago cut off from the mainland. The crumbling city is filled with the dead and denizens who have made it a world full of anarchy, danger, beauty, and terror.",
					popularity: 170.658,
					poster_path: "/wq3vuQzQgbS83zX3malAFWMsSwX.jpg",
					first_air_date: "2023-06-18",
					name: "The Walking Dead: Dead City",
					vote_average: 8.179,
					vote_count: 392,
				},
				{
					adult: false,
					backdrop_path: "/1gajPADcRyzmYvfAefbJwhCy4bk.jpg",
					genre_ids: [80, 18, 10759],
					id: 72710,
					origin_country: ["US"],
					original_language: "en",
					original_name:
						"The Continental: From the World of John Wick",
					overview:
						"Winston Scott is roped into a world of assassins and must make things right after his brother's attack on the Continental hotel.",
					popularity: 90.794,
					poster_path: "/fRORutvof4Y3tWkubhWKb9Z3Wc1.jpg",
					first_air_date: "2023-09-22",
					name: "The Continental: From the World of John Wick",
					vote_average: 7.5,
					vote_count: 371,
				},
				{
					adult: false,
					backdrop_path: "/179sUCj5AcFKdQpvDhkIX15NRgy.jpg",
					genre_ids: [18, 10759, 80],
					id: 146176,
					origin_country: ["ES"],
					original_language: "es",
					original_name: "Berlín",
					overview:
						"During his glory days, Berlin and a gang assembled in Paris for one of his greatest plans ever: stealing 44 million euros' worth of jewels in one night.",
					popularity: 120.145,
					poster_path: "/69YuvoiWTtK6oyYH2Jl4Q6SgZ59.jpg",
					first_air_date: "2023-12-29",
					name: "Berlin",
					vote_average: 7.638,
					vote_count: 363,
				},
				{
					adult: false,
					backdrop_path: "/nI8uQAU8KFXYIIRz6jdL0pmC3eL.jpg",
					genre_ids: [10759, 10765, 18, 10751],
					id: 103540,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Percy Jackson and the Olympians",
					overview:
						"Percy Jackson is on a dangerous quest. Outrunning monsters and outwitting gods, he must journey across America to return Zeus' master bolt and stop an all-out war. With the help of his quest mates Annabeth and Grover, Percy's journey will lead him closer to the answers he seeks: how to fit into a world where he feels out of place, and find out who he's destined to be.",
					popularity: 210.23,
					poster_path: "/c9loCTYWZpzYBTJBvE3DtRw4DBb.jpg",
					first_air_date: "2023-12-19",
					name: "Percy Jackson and the Olympians",
					vote_average: 7.401,
					vote_count: 352,
				},
				{
					adult: false,
					backdrop_path: "/AsmNm6f83DpllBL4VxcxwTR6S5W.jpg",
					genre_ids: [18],
					id: 196454,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Queen Charlotte: A Bridgerton Story",
					overview:
						"The story of how the young Queen Charlotte’s marriage to King George sparked both a great love story and a societal shift, creating the world of the Ton inherited by the characters in Bridgerton.",
					popularity: 64.113,
					poster_path: "/kFSaVIlBRycGNfrLzJZX7dgSQ1o.jpg",
					first_air_date: "2023-05-04",
					name: "Queen Charlotte: A Bridgerton Story",
					vote_average: 8.074,
					vote_count: 349,
				},
			],
			total_pages: 598,
			total_results: 11959,
		};
	} else if (query === "movie") {
		data = {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: "/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
					genre_ids: [878, 28, 80],
					id: 932420,
					original_language: "en",
					original_title: "Code 8 Part II",
					overview:
						"In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
					popularity: 873.449,
					poster_path: "/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
					release_date: "2024-02-27",
					title: "Code 8 Part II",
					video: false,
					vote_average: 6.553,
					vote_count: 160,
				},
				{
					adult: false,
					backdrop_path: "/gzlprPDmKCS4bUT4BxQZmJfpMX9.jpg",
					genre_ids: [878, 18],
					id: 636706,
					original_language: "en",
					original_title: "Spaceman",
					overview:
						"During a research mission, an astronaut discovers that his marriage is in trouble. Luckily, he has the help of a mysterious creature hidden in his ship.",
					popularity: 417.245,
					poster_path: "/5hnFFOWEchErNVr0wMLWFEob3q1.jpg",
					release_date: "2024-02-23",
					title: "Spaceman",
					video: false,
					vote_average: 6.638,
					vote_count: 178,
				},
				{
					adult: false,
					backdrop_path: "/zLj0peaxy5y2SlC6wNIQ4V0pfqg.jpg",
					genre_ids: [16, 10751, 35, 14],
					id: 1139829,
					original_language: "en",
					original_title: "Orion and the Dark",
					overview:
						"A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.",
					popularity: 268.1,
					poster_path: "/uHiXFLMlnl5jBjtfOliapN16yBD.jpg",
					release_date: "2024-02-02",
					title: "Orion and the Dark",
					video: false,
					vote_average: 6.704,
					vote_count: 299,
				},
				{
					adult: false,
					backdrop_path: "/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg",
					genre_ids: [28, 35, 80],
					id: 955916,
					original_language: "en",
					original_title: "Lift",
					overview:
						"An international heist crew, led by Cyrus Whitaker, race to lift $500 million in gold from a passenger plane at 40,000 feet.",
					popularity: 186.917,
					poster_path: "/46sp1Z9b2PPTgCMyA87g9aTLUXi.jpg",
					release_date: "2024-01-10",
					title: "Lift",
					video: false,
					vote_average: 6.569,
					vote_count: 896,
				},
				{
					adult: false,
					backdrop_path: "/nqywbJGJ4yfUGzumvd5gmGxchjn.jpg",
					genre_ids: [53],
					id: 1090874,
					original_language: "en",
					original_title: "Mea Culpa",
					overview:
						"A criminal defense attorney must choose between family, duty and her own dangerous desires when she takes on the case of an artist accused of murder.",
					popularity: 114.42,
					poster_path: "/roxD9VCTTXYfPjVj9HiSC5IMtc7.jpg",
					release_date: "2024-02-22",
					title: "Mea Culpa",
					video: false,
					vote_average: 5.708,
					vote_count: 77,
				},
				{
					adult: false,
					backdrop_path: "/4XgQ3Uxu2XbZbs2dZ2TQu6Uju3s.jpg",
					genre_ids: [10749, 35],
					id: 843617,
					original_language: "en",
					original_title: "Players",
					overview:
						'New York sportswriter Mack has spent years devising successful hook-up "plays" with her friends, but when she unexpectedly falls for one of her targets, she must learn what it takes to go from simply scoring to playing for keeps.',
					popularity: 103.831,
					poster_path: "/eA94hAGntLm7Lfol5FQJNxd53Hw.jpg",
					release_date: "2024-02-14",
					title: "Players",
					video: false,
					vote_average: 6.098,
					vote_count: 132,
				},
				{
					adult: false,
					backdrop_path: "/oXBJabf5KrKPRBKiFtqIKmWUEvl.jpg",
					genre_ids: [35],
					id: 1239159,
					original_language: "en",
					original_title: "Mike Epps: Ready to Sell Out",
					overview:
						"Mike Epps keeps it real as he riffs on poor personal hygiene, failing at infidelity and waging war on work husbands in this stand-up comedy special.",
					popularity: 90.433,
					poster_path: "/pyyl6QtYhZIc6Rs3tnN1M6c4Bjs.jpg",
					release_date: "2024-02-19",
					title: "Mike Epps: Ready to Sell Out",
					video: false,
					vote_average: 0,
					vote_count: 0,
				},
				{
					adult: false,
					backdrop_path: "/2T2NU30YsXwk0Ir4Vi0IDTaGYGC.jpg",
					genre_ids: [35, 10749],
					id: 1237835,
					original_language: "en",
					original_title: "A Soweto Love Story",
					overview:
						"Desperate for her three single sons to get married, a mother promises her house to the first one to tie the knot, setting off a race to the altar.",
					popularity: 39.777,
					poster_path: "/lNxLPPXAR13sjNIBGIncnR13v6E.jpg",
					release_date: "2024-02-14",
					title: "A Soweto Love Story",
					video: false,
					vote_average: 4.462,
					vote_count: 13,
				},
				{
					adult: false,
					backdrop_path: "/yLtSpzKeGKx5aa4oTLV8y00RxHf.jpg",
					genre_ids: [99, 18],
					id: 1168709,
					original_language: "en",
					original_title: "Einstein and the Bomb",
					overview:
						"What happened after Einstein fled Nazi Germany? Using archival footage and his own words, this docudrama dives into the mind of a tortured genius.",
					popularity: 32.405,
					poster_path: "/hWRKHXKfu2WJGICdVpKZ0jEKsbp.jpg",
					release_date: "2024-02-16",
					title: "Einstein and the Bomb",
					video: false,
					vote_average: 5.802,
					vote_count: 43,
				},
				{
					adult: false,
					backdrop_path: "/zMZUzJOMtdT0UyevOsq9F6qTooS.jpg",
					genre_ids: [80, 99],
					id: 1229958,
					original_language: "en",
					original_title: "Lover, Stalker, Killer",
					overview:
						"In this twisting documentary, a mechanic tries online dating for the first time and meets a woman who takes romantic obsession to a deadly extreme.",
					popularity: 30.417,
					poster_path: "/f5uojWzwJTCHBIV3rmGPTmQG7TF.jpg",
					release_date: "2024-02-09",
					title: "Lover, Stalker, Killer",
					video: false,
					vote_average: 6.868,
					vote_count: 57,
				},
				{
					adult: false,
					backdrop_path: "/4KBoRsiVHAWAgWBbVKv8UUFGpYS.jpg",
					genre_ids: [35],
					id: 1244801,
					original_language: "en",
					original_title: "Hannah Gadsby's Gender Agenda",
					overview:
						"Genderqueer comics from around the world take the stage at London's Alexandra Palace in this comedy showcase hosted by the award-winning Hannah Gadsby.",
					popularity: 20.626,
					poster_path: "/sm5vjpFDdfe2TVIvyXE19ZhOv1o.jpg",
					release_date: "2024-03-04",
					title: "Hannah Gadsby's Gender Agenda",
					video: false,
					vote_average: 0,
					vote_count: 0,
				},
				{
					adult: false,
					backdrop_path: "/37LyKFPr7ksoXMea7MIWFa8Llaj.jpg",
					genre_ids: [27, 53],
					id: 714669,
					original_language: "en",
					original_title: "Run Rabbit Run",
					overview:
						"Sarah is a fertility doctor with a firm understanding of the cycle of life. When she is forced to make sense of the increasingly strange behavior of her young daughter Mia, she must challenge her own beliefs and confront a ghost from her past.",
					popularity: 22.891,
					poster_path: "/cgetiYyTqJ4CMmPmvDw30nnYj1f.jpg",
					release_date: "2024-01-25",
					title: "Run Rabbit Run",
					video: false,
					vote_average: 5.063,
					vote_count: 8,
				},
				{
					adult: false,
					backdrop_path: "/tZz7QEwcTFc8GcuPCqAg1c4K9QS.jpg",
					genre_ids: [],
					id: 1245423,
					original_language: "en",
					original_title: "The Netflix Slam",
					overview:
						"It's the legend vs. the prodigy as Rafael Nadal takes on Carlos Alcaraz in an exhibition match at Las Vegas' Michelob ULTRA Arena.",
					popularity: 20.278,
					poster_path: "/xZmgedVstqX8gWNbaxNO5YJ72GL.jpg",
					release_date: "2024-03-03",
					title: "The Netflix Slam",
					video: false,
					vote_average: 0,
					vote_count: 0,
				},
				{
					adult: false,
					backdrop_path: "/dUz8n64kOSCpUZYELEfucDisijl.jpg",
					genre_ids: [18],
					id: 1169455,
					original_language: "en",
					original_title: "The After",
					overview:
						"After losing a family member to a violent crime, a shattered rideshare driver picks up a passenger that forces him to confront his grief.",
					popularity: 21.783,
					poster_path: "/su2APJLMwx4IzAcPHhvoak2k2U1.jpg",
					release_date: "2024-02-16",
					title: "The After",
					video: false,
					vote_average: 5.7,
					vote_count: 29,
				},
				{
					adult: false,
					backdrop_path: "/Amb16QpgV4ZxdU8C80SW6JNySp9.jpg",
					genre_ids: [99, 10402],
					id: 1226841,
					original_language: "en",
					original_title: "The Greatest Night in Pop",
					overview:
						"In 1985, 46 music icons, including Lionel Richie, Michael Jackson, Bruce Springsteen, Cyndi Lauper, Diana Ross, and Stevie Wonder, came together for the most star-studded recording session in history. This is the untold story of the legendary global pop song “We Are the World” — which very nearly didn’t happen.",
					popularity: 18.394,
					poster_path: "/jDz4wFujk94tQP9Sx6EMKDULvkn.jpg",
					release_date: "2024-01-19",
					title: "The Greatest Night in Pop",
					video: false,
					vote_average: 8.066,
					vote_count: 129,
				},
				{
					adult: false,
					backdrop_path: "/vzO729sITNJ1jB6Y9AJpIhlbvb2.jpg",
					genre_ids: [99, 80],
					id: 1213997,
					original_language: "en",
					original_title: "Bitconned",
					overview:
						"In this true-crime documentary, three guys exploit the freewheeling cryptocurrency market to scam millions from investors and bankroll lavish lifestyles.",
					popularity: 9.273,
					poster_path: "/6YZmezBcTwL9KUn5kkygAvrJ1fx.jpg",
					release_date: "2024-01-01",
					title: "Bitconned",
					video: false,
					vote_average: 5.948,
					vote_count: 29,
				},
				{
					adult: false,
					backdrop_path: "/rVzOnqaKHEoH4Ky74i4CUUViKy1.jpg",
					genre_ids: [35],
					id: 1227770,
					original_language: "en",
					original_title: "Taylor Tomlinson: Have It All",
					overview:
						"Can Taylor Tomlinson have it all? From dating woes to dream jobs to inventive dirty talk, she shares life's ups and downs in this stand-up comedy special.",
					popularity: 10.423,
					poster_path: "/xotV6MkshGfLWIUi3su6Pdajrt3.jpg",
					release_date: "2024-02-12",
					title: "Taylor Tomlinson: Have It All",
					video: false,
					vote_average: 7.357,
					vote_count: 14,
				},
				{
					adult: false,
					backdrop_path: "/sn9Xmf4o4LlLxN4zSp1SrN4pLdt.jpg",
					genre_ids: [35],
					id: 1250892,
					original_language: "en",
					original_title:
						"Chappelle's Home Team - Donnell Rawlings: A New Day",
					overview:
						"Donnell Rawlings riffs on toxic relationships, getting older, visiting New Zealand and his secret to co-parenting a young son in this stand-up special.",
					popularity: 5.252,
					poster_path: "/43TKQr4JnRe5ydmmKkASFxJYG0J.jpg",
					release_date: "2024-02-26",
					title: "Chappelle's Home Team - Donnell Rawlings: A New Day",
					video: false,
					vote_average: 6,
					vote_count: 1,
				},
				{
					adult: false,
					backdrop_path: "/5vX7c2HH2h8Mt7XyrYmNJyT1Wf0.jpg",
					genre_ids: [35],
					id: 1214980,
					original_language: "en",
					original_title: "Jacqueline Novak: Get on Your Knees",
					overview:
						"Comedian Jacqueline Novak delivers a funny and philosophical meditation on sex, coming-of-age and a certain body part in this intimate stand-up special.",
					popularity: 4.569,
					poster_path: "/hC3tjla6HQCIj09fgVE5qdixNGb.jpg",
					release_date: "2024-01-22",
					title: "Jacqueline Novak: Get on Your Knees",
					video: false,
					vote_average: 6.3,
					vote_count: 6,
				},
				{
					adult: false,
					backdrop_path: "/iiKoiSgHEZzUNLHiMrgkPyNCQl0.jpg",
					genre_ids: [35],
					id: 1218509,
					original_language: "en",
					original_title: "Pete Davidson: Turbo Fonzarelli",
					overview:
						"Pete Davidson's fourth comedy special explores what it means to grow up, turning 30, love, life, and living in the woods.",
					popularity: 2.545,
					poster_path: "/bhOPqjS8D3uCvFHb695WIHi0UKA.jpg",
					release_date: "2024-01-09",
					title: "Pete Davidson: Turbo Fonzarelli",
					video: false,
					vote_average: 6.2,
					vote_count: 13,
				},
			],
			total_pages: 2,
			total_results: 24,
		};
	} else if (query === "tv") {
		data = {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: "/imlTCObfzISogbvcwB1dokoXAIc.jpg",
					genre_ids: [10765, 10759, 18],
					id: 82452,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Avatar: The Last Airbender",
					overview:
						"A young boy known as the Avatar must master the four elemental powers to save a world at war — and fight a ruthless enemy bent on stopping him.",
					popularity: 1393.277,
					poster_path: "/lzZpWEaqzP0qVA5nkCc5ASbNcSy.jpg",
					first_air_date: "2024-02-22",
					name: "Avatar: The Last Airbender",
					vote_average: 8.19,
					vote_count: 428,
				},
				{
					adult: false,
					backdrop_path: "/vCFqjjJBEbRSHxLaoaBN29atLky.jpg",
					genre_ids: [18],
					id: 240667,
					origin_country: ["GB"],
					original_language: "en",
					original_name: "One Day",
					overview:
						"After spending graduation night together, Emma and Dexter go their separate ways — but their lives remain intertwined.",
					popularity: 162.094,
					poster_path: "/smBWt8rHCCavV88C5gQVjh0NUFa.jpg",
					first_air_date: "2024-02-08",
					name: "One Day",
					vote_average: 7.827,
					vote_count: 78,
				},
				{
					adult: false,
					backdrop_path: "/nj06Yo0yVzI7jx6novjyGOyNQKC.jpg",
					genre_ids: [18, 80],
					id: 137893,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Griselda",
					overview:
						"Chronicles the life of Griselda Blanco, who created one of the most profitable cartels in history. A devoted mother, Blanco’s lethal blend of charm and unsuspecting savagery helped her expertly navigate between family and business leading her to become widely known as the “Black Widow”.",
					popularity: 131.064,
					poster_path: "/nhEtK1lJKb3kqBtDBDXynGr3hJL.jpg",
					first_air_date: "2024-01-25",
					name: "Griselda",
					vote_average: 7.452,
					vote_count: 189,
				},
				{
					adult: false,
					backdrop_path: "/9h15FWJFZstTGLTUVbToCEFdH9F.jpg",
					genre_ids: [18, 10759, 80],
					id: 227004,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Brothers Sun",
					overview:
						"When a mysterious enemy targets his family, a Taipei triad member heads to Los Angeles to protect his strong-willed mother and oblivious younger brother.",
					popularity: 132.597,
					poster_path: "/aTPMj3Bqb0WfHsIv8zUOROSjb7S.jpg",
					first_air_date: "2024-01-04",
					name: "The Brothers Sun",
					vote_average: 7.753,
					vote_count: 89,
				},
				{
					adult: false,
					backdrop_path: "/5QlPMpggN5pLAZWpae0doDgRNZi.jpg",
					genre_ids: [18, 80, 9648],
					id: 220801,
					origin_country: ["GB"],
					original_language: "en",
					original_name: "Fool Me Once",
					overview:
						"When ex-soldier Maya sees her murdered husband on a secret nanny cam, she uncovers a deadly conspiracy that stretches deep into the past.",
					popularity: 124.203,
					poster_path: "/Ertv4WLEyHgi8zN4ldOKgPcGAZ.jpg",
					first_air_date: "2024-01-01",
					name: "Fool Me Once",
					vote_average: 7.277,
					vote_count: 206,
				},
				{
					adult: false,
					backdrop_path: "/gBh9HHrpNozKJvsaLuU3uCnKwjx.jpg",
					genre_ids: [16, 10762, 10759],
					id: 235995,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Hot Wheels Let's Race",
					overview:
						"Six young hopefuls at the Hot Wheels Ultimate Garage Racing Camp learn the skills they need to become the next generation of amazing racers.",
					popularity: 120.083,
					poster_path: "/ketVrjhxmXMogzX360DnrIVAeK5.jpg",
					first_air_date: "2024-03-04",
					name: "Hot Wheels Let's Race",
					vote_average: 10,
					vote_count: 1,
				},
				{
					adult: false,
					backdrop_path: "/gJd7leBA9VvRefWLYuVFHSBPVoW.jpg",
					genre_ids: [16, 10759, 10765],
					id: 234721,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Masters of the Universe: Revolution",
					overview:
						"It's technology versus magic as He-Man and friends fight back against the shadowy forces of Skeletor in an epic battle for the heart of Eternia.",
					popularity: 59.248,
					poster_path: "/s54EXuPe3BlQ4PlotUznkuIHgd9.jpg",
					first_air_date: "2024-01-25",
					name: "Masters of the Universe: Revolution",
					vote_average: 8.237,
					vote_count: 38,
				},
				{
					adult: false,
					backdrop_path: "/miqJXBf8WUv9S9klUanjkO6BtsU.jpg",
					genre_ids: [99, 80],
					id: 244616,
					origin_country: ["US"],
					original_language: "en",
					original_name: "American Conspiracy: The Octopus Murders",
					overview:
						"An investigative journalist pursuing a political conspiracy known as the Octopus is found dead in his hotel room. Decades later, new details emerge.",
					popularity: 37.568,
					poster_path: "/lrcJuD9HPu5ZVcZaLk9cB0xufi5.jpg",
					first_air_date: "2024-02-28",
					name: "American Conspiracy: The Octopus Murders",
					vote_average: 6.833,
					vote_count: 6,
				},
				{
					adult: false,
					backdrop_path: "/v0cVF5nO5FvcF5oLyQX5ayYpypu.jpg",
					genre_ids: [18, 80, 9648],
					id: 209332,
					origin_country: ["AU"],
					original_language: "en",
					original_name: "Boy Swallows Universe",
					overview:
						"A young boy growing up in the suburbs of 1980s Brisbane faces the harsh realities of life — and the looming dangers that threaten his family.",
					popularity: 41.055,
					poster_path: "/nb0ek7qonE0YkyaB4dsAw5J9NoH.jpg",
					first_air_date: "2024-01-11",
					name: "Boy Swallows Universe",
					vote_average: 7.383,
					vote_count: 60,
				},
				{
					adult: false,
					backdrop_path: "/wb8FEe569dxey9PwQMqqO5yKTMf.jpg",
					genre_ids: [99, 80],
					id: 242845,
					origin_country: ["GB"],
					original_language: "en",
					original_name: "American Nightmare",
					overview:
						"After a harrowing home invasion and kidnapping in 2015, a couple is accused of staging the ordeal when the woman reappears in this true-crime docuseries.",
					popularity: 24.611,
					poster_path: "/y7dQEXvqzNxm3sFY3VV7PqKeHzB.jpg",
					first_air_date: "2024-01-17",
					name: "American Nightmare",
					vote_average: 7.4,
					vote_count: 40,
				},
				{
					adult: false,
					backdrop_path: "/of4G6KnanGQ0MYcIvl1p8aDAe9N.jpg",
					genre_ids: [99, 18],
					id: 242392,
					origin_country: ["GB"],
					original_language: "en",
					original_name: "Alexander: The Making of a God",
					overview:
						"Expert interviews and gripping reenactments combine to reveal the extraordinary life of Alexander the Great and his burning desire to conquer the world.",
					popularity: 29.466,
					poster_path: "/tKUTpdyg0wGfIYplIAfkN6hDbRw.jpg",
					first_air_date: "2024-01-31",
					name: "Alexander: The Making of a God",
					vote_average: 6.8,
					vote_count: 25,
				},
				{
					adult: false,
					backdrop_path: "/edLxbkOKXtKPmk6Qxzgutol0uwd.jpg",
					genre_ids: [10764],
					id: 244587,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Dinner Time Live with David Chang",
					overview:
						"Chef David Chang hosts an unfiltered dining experience as he cooks for celebrity guests and shares culinary secrets.",
					popularity: 17.058,
					poster_path: "/6isaKyEbUyTlks7eWxTwfAUpXA3.jpg",
					first_air_date: "2024-01-25",
					name: "Dinner Time Live with David Chang",
					vote_average: 0,
					vote_count: 0,
				},
				{
					adult: false,
					backdrop_path: "/nd70axjGzfprChYTDbbGDndHFVl.jpg",
					genre_ids: [18, 35],
					id: 243861,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Vince Staples Show",
					overview:
						"Kind of famous and sort of rich, rapper and actor Vince Staples navigates the challenges and surprises of everyday life in his hometown of The Beach.",
					popularity: 13.471,
					poster_path: "/gyUKo6ILKVwuiVq4EWv1avEXpBp.jpg",
					first_air_date: "2024-02-15",
					name: "The Vince Staples Show",
					vote_average: 6.25,
					vote_count: 8,
				},
				{
					adult: false,
					backdrop_path: "/uUSjHNkxjb23e5kylpDp747iF7M.jpg",
					genre_ids: [99],
					id: 245551,
					origin_country: ["GB"],
					original_language: "en",
					original_name: "Can I Tell You a Secret?",
					overview:
						"Three women's lives are changed forever when a prolific stalker infiltrates their social media accounts. And they're only a fraction of his many victims.",
					popularity: 18.568,
					poster_path: "/cWyIMECkpTsLslyyuH0RaAAw5Vh.jpg",
					first_air_date: "2024-02-21",
					name: "Can I Tell You a Secret?",
					vote_average: 6.5,
					vote_count: 9,
				},
				{
					adult: false,
					backdrop_path: "/q53nYvorj8kJAGYywWRT5EaKoTM.jpg",
					genre_ids: [10762, 16, 10765],
					id: 235997,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Dee & Friends in Oz",
					overview:
						"When a mysterious key transports her to the land of Oz, a regular kid named Dee goes on a musical journey to save magic — and be the hero of the story.",
					popularity: 13.947,
					poster_path: "/2JpmHa3kETozHCRckt3RTc9WQFJ.jpg",
					first_air_date: "2024-02-05",
					name: "Dee & Friends in Oz",
					vote_average: 0,
					vote_count: 0,
				},
				{
					adult: false,
					backdrop_path: "/2LttijRpmEfR2OlPzEO2BC5A8Og.jpg",
					genre_ids: [99, 10764],
					id: 242394,
					origin_country: ["GB"],
					original_language: "en",
					original_name: "Six Nations: Full Contact",
					overview:
						"Round after round, match after match, Europe's best teams battle to take home the trophy in the 2023 Six Nations Championship.",
					popularity: 15.619,
					poster_path: "/spnLKY3togIef7m8kpA7dH4rNlf.jpg",
					first_air_date: "2024-01-24",
					name: "Six Nations: Full Contact",
					vote_average: 7.6,
					vote_count: 4,
				},
				{
					adult: false,
					backdrop_path: "/iIdEmwWVrv5cfDDup3JuxdMwSUp.jpg",
					genre_ids: [10764],
					id: 241168,
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Trust: A Game of Greed",
					overview:
						"In this reality series, strangers compete to share a quarter of a million dollars. Will they split it evenly — or cut each other out to raise their take?",
					popularity: 14.509,
					poster_path: "/pA1wT1JMjoZNf7vVIzEEJ6Gvp1j.jpg",
					first_air_date: "2024-01-10",
					name: "The Trust: A Game of Greed",
					vote_average: 6.143,
					vote_count: 7,
				},
				{
					adult: false,
					backdrop_path: "/hPP2b6CbhM8pzDwRKou5tv3KhZp.jpg",
					genre_ids: [99],
					id: 243348,
					origin_country: ["US"],
					original_language: "en",
					original_name: "NASCAR: Full Speed",
					overview:
						"Fueled by passion and NASCAR Cup glory, drivers and their teams compete for the championship and the chance to make history in this sports docuseries.",
					popularity: 15.683,
					poster_path: "/fXhZCpFlFXST8qZt2dYT4XTeF1E.jpg",
					first_air_date: "2024-01-30",
					name: "NASCAR: Full Speed",
					vote_average: 8,
					vote_count: 3,
				},
				{
					adult: false,
					backdrop_path: "/qkbWY2QSiGQnA0vXG5Ld96WJsLL.jpg",
					genre_ids: [99],
					id: 241849,
					origin_country: ["US"],
					original_language: "en",
					original_name: "You Are What You Eat: A Twin Experiment",
					overview:
						"Identical twins change their diets and lifestyles for eight weeks in a unique scientific experiment designed to explore how certain foods impact the body.",
					popularity: 8.861,
					poster_path: "/uRy6fpVNrxtjt03YgO2YdY4yoje.jpg",
					first_air_date: "2024-01-01",
					name: "You Are What You Eat: A Twin Experiment",
					vote_average: 6.6,
					vote_count: 20,
				},
				{
					adult: false,
					backdrop_path: null,
					genre_ids: [],
					id: 242768,
					origin_country: ["US"],
					original_language: "en",
					original_name: "Peaky Blinders: How We Made Them Dance",
					overview:
						"Peaky Blinders writer and creator Steven Knight and choreographer Benoit Swan Pouffer of the celebrated Rambert Dance Company discuss the collaboration that resulted in one of the most unexpected and tantalising stage productions of recent years: Peaky Blinders: The Redemption of Thomas Shelby.\n\nWith a mesmerising performance in the lead role by Guillaume Queau, this dance extravaganza doesn’t shy away from the shocking violence of the drama that has won fans across the world, telling the story of Thomas during World War I, before he transformed himself into the notorious crime boss of the TV series.\n\nSteven and Benoit share their insights into the making of the show, the challenges they faced along the way, and how this unlikely idea became a remarkable reality.",
					popularity: 1.643,
					poster_path: null,
					first_air_date: "2024-01-01",
					name: "Peaky Blinders: How We Made Them Dance",
					vote_average: 0,
					vote_count: 0,
				},
			],
			total_pages: 1,
			total_results: 20,
		};
	}

	return Response.json({ data });
}
